### ISSUE TITLE
--offline flag doesn't work as expected

### ISSUE THREAD

**Issue by matsuro-hadouken** [regen-network/testnets#883]
`--offline` flag not been noticed by client.

* Processed transaction with

```json
regen tx bank send "$from_key" "$destination" "$AMOUNT" \
        --node "$rpc_address" \
        --chain-id "$chain_name" -y \
        --memo "$memo" \
        --offline \
        --fees 5000utree
```

Broadcast transaction to network

https://aplikigo.regen.aneka.io/txs/B3B274BE24B7951FF3549418044C1F4F5E6F911460B2CFF7AA31690819B00542

* Expected

Doesn't broadcast

**Comment by ryanchristo** [comment]
As far as I understand, cosmos sdk requires `offline` to be used with `generate-only` when calling the `tx` command. I'm not entirely sure why but this is expected behavior given the current implementation. If improvements should be made, the cosmos sdk repository would be the best place to open an issue.
